---
notifications:
  email:
    - 'cbm+travis@x32.dk'
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
rvm:
  - 2.7.0
env:
  - PUPPET_VERSION="~> 5.5.22"
matrix:
before_script: 'gem install --no-document bundler'
script: 'bundle exec rake validate && bundle exec rake lint && SPEC_OPTS="--format documentation" bundle exec rake spec'
gemfile: Gemfile
